spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    initialization-mode: always
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      fail-on-empty-beans: false
name: kim
logging:
  path: logs
  level:
    spring:
      springframework: info
    examples:
      boot:
        myboard: DEBUG


serverinfo:
  address: localhost
  port: 0000
---
spring:
    profiles: dev
name : lee

---
spring:
    profiles: real
name : kang


